version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies
      - run:
          name: Install Node Depend.
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Building Project
          command: yarn build --runInBand
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo 'Deploy'

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - node/test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - node/test
